# For testing codes

In [1]:
import torch

In [19]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = [[x], [y]]
print(z)
torch.cat((torch.tensor([x]), torch.tensor([y])), 0)

[[tensor([1, 2, 3])], [tensor([4, 5, 6])]]


tensor([1, 2, 3, 4, 5, 6])

In [5]:
data = {}
data['labels'] = torch.Tensor()
print(data['labels'])
label1 = torch.tensor([1])
label2 = torch.tensor([2])
data['labels'] = label1
print(data['labels'])
data['labels'] = torch.cat((data['labels'], label2), 0)
print(data['labels'])

tensor([])
tensor([1])
tensor([1, 2])


In [3]:
a = torch.tensor([1,2,3,4,5,6])
a.reshape([2,3])
a

tensor([1, 2, 3, 4, 5, 6])